version: '3'

services:
  imgpush:
    image: hauxir/imgpush:latest
    container_name: imgpush
    env_file:
        - .env
    restart: always
    volumes:
      - "./data/images:/images"
    environment:
      - MAX_UPLOADS_PER_DAY=1000
      - MAX_UPLOADS_PER_HOUR=400
      - ALLOWED_ORIGINS=["*"]
      - NAME_STRATEGY=uuidv4
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.imgpush.rule=Host(`${SERVICE_URL}`) && PathPrefix(`/${SERVICE_PATH_IMGPUSH}`)"
      - "traefik.http.routers.imgpush.entrypoints=https"
      - "traefik.http.routers.imgpush.tls=true"
