version: '3'

services:
  imgpush:
    image: hauxir/imgpush:latest
    container_name: imgpush
    depends_on:
      - traefik
    env_file:
        - .env
    restart: always
    volumes:
      - "./data/images:/images"
    environment:
      - MAX_UPLOADS_PER_DAY=1000
      - MAX_UPLOADS_PER_HOUR=400
      - ALLOWED_ORIGINS=["*"]
      - NAME_STRATEGY=uuidv4
    networks:
      - proxy 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.imgpush.rule=Host(`${SERVICE_URL}`) && PathPrefix(`/${SERVICE_PATH_IMGPUSH}`)"
      - "traefik.http.routers.imgpush.middlewares=imgpush-stripprefix"
      - "traefik.http.middlewares.imgpush-stripprefix.stripprefix.prefixes=/${SERVICE_PATH_IMGPUSH}"
      - "traefik.http.routers.imgpush.entrypoints=websecure"
      - "traefik.http.routers.imgpush.tls=true"
      - "traefik.http.routers.imgpush.tls.certresolver=letsencrypt"

networks:
  proxy:
    external: true